package com.rays.form;

import javax.validation.constraints.NotEmpty;

import com.rays.common.BaseForm;
import com.rays.dto.ReportDTO;

public class ReportForm extends BaseForm {

	@NotEmpty(message = "Please enter report name")
	private String reportName;

	@NotEmpty(message = "Please enter generated by")
	private String generatedBy;

	@NotEmpty(message = "Please select report status")
	private String reportStatus;

	public String getReportName() {
		return reportName;
	}

	public void setReportName(String reportName) {
		this.reportName = reportName;
	}

	public String getGeneratedBy() {
		return generatedBy;
	}

	public void setGeneratedBy(String generatedBy) {
		this.generatedBy = generatedBy;
	}

	public String getReportStatus() {
		return reportStatus;
	}

	public void setReportStatus(String reportStatus) {
		this.reportStatus = reportStatus;
	}

	@Override
	public ReportDTO getDto() {

		ReportDTO dto = initDTO(new ReportDTO());

		dto.setReportName(reportName);
		dto.setGeneratedBy(generatedBy);
		dto.setReportStatus(reportStatus);

		return dto;
	}
}
